apiVersion: batch/v1
kind: Job
metadata:
  name: seed-openlibrary
  namespace: socialbook
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: alazar111/socialbook-backend:latest
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/socialbook
          command: ["node", "scripts/seed-openlibrary.js"]
