apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialbook
  namespace: socialbook
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - socialbook.46-62-130-16.nip.io
      secretName: socialbook-nip-tls
    - hosts:
        - api.socialbook.46-62-130-16.nip.io
      secretName: api-socialbook-nip-tls
  rules:
    - host: socialbook.46-62-130-16.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: api.socialbook.46-62-130-16.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
